cache:
  bundler: true
  directories:
    - .jekyll-metadata
    - Gemfile.lock
    - _site
    - node_modules
before_install: npm install
script: ./test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
