cache:
  bundler: true
  directories:
    - node_modules
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - nvm install
  - npm install
script: ./test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
