# metadata
title: Nick McCurdy
description: Software Engineer

# configuration
defaults:
  -
    values:
      layout: default
exclude:
  - "*.xcf"
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - test
  - vendor
incremental: true
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
sass:
  style: compressed
livereload: true
