title: Nicolas McCurdy
defaults:
  -
    values:
      layout: default
exclude:
  - "*.xcf"
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
sass:
  style: compressed
