#!/usr/bin/env bash
set -ev

# Check links
bundle exec htmlproofer _site \
       --check-external-hash \
       --ignore-files "_site/(projects|skills|talks)/index.html,/node_modules/" \
       --only-4xx \
       --swap-urls '^/apps/(.*)$:https\://nickmccurdy.com/apps/\1'

# Lint styles
node_modules/.bin/stylelint assets/style.scss
