#!/usr/bin/env bash
set -ev
# Build
if [ "$CI" != true ]
then  
  bundle exec jekyll build
fi

# Validate HTML
java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html _site

# Check links
bundle exec htmlproofer _site \
       --check-external-hash \
       --check-favicon \
       --check-html \
       --file-ignore "_site/(projects|skills|talks)/index.html,/node_modules/" \
       --url-swap '^/apps/(.*)$:https\://nickmccurdy.com/apps/\1'

# Lint styles
node_modules/.bin/stylelint assets/style.scss
