on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
      - uses: actions/configure-pages@v3
        id: pages
      - run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_ENV: production
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: ./test

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2